apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-ip-daemon
  namespace: kube-system
  labels:
    k8s-app: aws-ip-daemon
spec:
  selector:
    matchLabels:
      name: aws-ip-daemon
  template:
    metadata:
      labels:
        name: aws-ip-daemon
    spec:
      containers:
      - name: aws-ip-daemon
        image: xxxxxxxxx.dkr.ecr.us-east-2.amazonaws.com/aws-ip-daemon:0.1
        imagePullPolicy: Always
        args: [/bin/sh, -c, 'python3 -u assignPodAddress.pyc']
        resources:
          limits:
            memory: 400Mi
            cpu: 400m
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
